//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferencePhotos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateFileDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Dto")]
    public partial class CreateFileDto : object
    {
        
        private string abs_pathField;
        
        private string created_dateField;
        
        private string descriptionField;
        
        private string eventField;
        
        private string event_dateField;
        
        private string event_locationField;
        
        private System.Collections.Generic.List<ServiceReferencePhotos.PersonsDto> newPersonsField;
        
        private System.Collections.Generic.List<ServiceReferencePhotos.PropertyDto> newPropertiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string abs_path
        {
            get
            {
                return this.abs_pathField;
            }
            set
            {
                this.abs_pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string created_date
        {
            get
            {
                return this.created_dateField;
            }
            set
            {
                this.created_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string @event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string event_date
        {
            get
            {
                return this.event_dateField;
            }
            set
            {
                this.event_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string event_location
        {
            get
            {
                return this.event_locationField;
            }
            set
            {
                this.event_locationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePhotos.PersonsDto> newPersons
        {
            get
            {
                return this.newPersonsField;
            }
            set
            {
                this.newPersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePhotos.PropertyDto> newProperties
        {
            get
            {
                return this.newPropertiesField;
            }
            set
            {
                this.newPropertiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonsDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Dto")]
    public partial class PersonsDto : object
    {
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string relationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Dto")]
    public partial class PropertyDto : object
    {
        
        private string nameField;
        
        private string valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Files", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos", IsReference=true)]
    public partial class Files : object
    {
        
        private int IdField;
        
        private System.Collections.Generic.List<ServiceReferencePhotos.Persons> PersonsField;
        
        private string abs_pathField;
        
        private string created_dateField;
        
        private string descriptionField;
        
        private string eventField;
        
        private string event_dateField;
        
        private string event_locationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePhotos.Persons> Persons
        {
            get
            {
                return this.PersonsField;
            }
            set
            {
                this.PersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string abs_path
        {
            get
            {
                return this.abs_pathField;
            }
            set
            {
                this.abs_pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string created_date
        {
            get
            {
                return this.created_dateField;
            }
            set
            {
                this.created_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string @event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string event_date
        {
            get
            {
                return this.event_dateField;
            }
            set
            {
                this.event_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string event_location
        {
            get
            {
                return this.event_locationField;
            }
            set
            {
                this.event_locationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persons", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos", IsReference=true)]
    public partial class Persons : object
    {
        
        private System.Collections.Generic.List<ServiceReferencePhotos.Files> FilesField;
        
        private int IdField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string relationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePhotos.Files> Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Properties", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos", IsReference=true)]
    public partial class Properties : object
    {
        
        private System.Collections.Generic.List<ServiceReferencePhotos.Files> FilesField;
        
        private int IdField;
        
        private string nameField;
        
        private string valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePhotos.Files> Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePhotos.IMyPhotos")]
    public interface IMyPhotos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/AddNewFile", ReplyAction="http://tempuri.org/InterfaceFiles/AddNewFileResponse")]
        System.Threading.Tasks.Task<ServiceReferencePhotos.Files> AddNewFileAsync(ServiceReferencePhotos.CreateFileDto fileRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/GetAllFilesPaths", ReplyAction="http://tempuri.org/InterfaceFiles/GetAllFilesPathsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllFilesPathsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/GetFilesByProperty", ReplyAction="http://tempuri.org/InterfaceFiles/GetFilesByPropertyResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetFilesByPropertyAsync(string propertyName, string propertyValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/GetFilesByRelation", ReplyAction="http://tempuri.org/InterfaceFiles/GetFilesByRelationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetFilesByRelationAsync(string relation_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/ModifyFile", ReplyAction="http://tempuri.org/InterfaceFiles/ModifyFileResponse")]
        System.Threading.Tasks.Task ModifyFileAsync(ServiceReferencePhotos.CreateFileDto fileRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUsers/AddNewPerson", ReplyAction="http://tempuri.org/InterfaceUsers/AddNewPersonResponse")]
        System.Threading.Tasks.Task<ServiceReferencePhotos.Persons> AddNewPersonAsync(string firstname, string lastname, string relation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperties/AddNewProperty", ReplyAction="http://tempuri.org/InterfaceProperties/AddNewPropertyResponse")]
        System.Threading.Tasks.Task<ServiceReferencePhotos.Properties> AddNewPropertyAsync(string name, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperties/Check_If_Property_Exists", ReplyAction="http://tempuri.org/InterfaceProperties/Check_If_Property_ExistsResponse")]
        System.Threading.Tasks.Task<ServiceReferencePhotos.Properties> Check_If_Property_ExistsAsync(string propertyName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMyPhotosChannel : ServiceReferencePhotos.IMyPhotos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MyPhotosClient : System.ServiceModel.ClientBase<ServiceReferencePhotos.IMyPhotos>, ServiceReferencePhotos.IMyPhotos
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MyPhotosClient() : 
                base(MyPhotosClient.GetDefaultBinding(), MyPhotosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMyPhotos.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosClient(EndpointConfiguration endpointConfiguration) : 
                base(MyPhotosClient.GetBindingForEndpoint(endpointConfiguration), MyPhotosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MyPhotosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MyPhotosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePhotos.Files> AddNewFileAsync(ServiceReferencePhotos.CreateFileDto fileRequest)
        {
            return base.Channel.AddNewFileAsync(fileRequest);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllFilesPathsAsync()
        {
            return base.Channel.GetAllFilesPathsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetFilesByPropertyAsync(string propertyName, string propertyValue)
        {
            return base.Channel.GetFilesByPropertyAsync(propertyName, propertyValue);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetFilesByRelationAsync(string relation_type)
        {
            return base.Channel.GetFilesByRelationAsync(relation_type);
        }
        
        public System.Threading.Tasks.Task ModifyFileAsync(ServiceReferencePhotos.CreateFileDto fileRequest)
        {
            return base.Channel.ModifyFileAsync(fileRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePhotos.Persons> AddNewPersonAsync(string firstname, string lastname, string relation)
        {
            return base.Channel.AddNewPersonAsync(firstname, lastname, relation);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePhotos.Properties> AddNewPropertyAsync(string name, string value)
        {
            return base.Channel.AddNewPropertyAsync(name, value);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePhotos.Properties> Check_If_Property_ExistsAsync(string propertyName)
        {
            return base.Channel.Check_If_Property_ExistsAsync(propertyName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMyPhotos))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMyPhotos))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MyPhotosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMyPhotos);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MyPhotosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMyPhotos);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMyPhotos,
        }
    }
}
