//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Dto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateFileDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Dto")]
    public partial class CreateFileDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string abs_pathField;
        
        private string created_dateField;
        
        private string descriptionField;
        
        private string eventField;
        
        private string event_dateField;
        
        private string event_locationField;
        
        private System.Collections.Generic.List<MyPhotos.Dto.PersonsDto> newPersonsField;
        
        private System.Collections.Generic.List<MyPhotos.Dto.PropertyDto> newPropertiesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string abs_path
        {
            get
            {
                return this.abs_pathField;
            }
            set
            {
                this.abs_pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string created_date
        {
            get
            {
                return this.created_dateField;
            }
            set
            {
                this.created_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string @event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string event_date
        {
            get
            {
                return this.event_dateField;
            }
            set
            {
                this.event_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string event_location
        {
            get
            {
                return this.event_locationField;
            }
            set
            {
                this.event_locationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotos.Dto.PersonsDto> newPersons
        {
            get
            {
                return this.newPersonsField;
            }
            set
            {
                this.newPersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotos.Dto.PropertyDto> newProperties
        {
            get
            {
                return this.newPropertiesField;
            }
            set
            {
                this.newPropertiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonsDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Dto")]
    public partial class PersonsDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string relationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Dto")]
    public partial class PropertyDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nameField;
        
        private string valueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}
namespace MyPhotos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Files", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos", IsReference=true)]
    public partial class Files : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Collections.Generic.List<MyPhotos.Persons> PersonsField;
        
        private string abs_pathField;
        
        private string created_dateField;
        
        private string descriptionField;
        
        private string eventField;
        
        private string event_dateField;
        
        private string event_locationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotos.Persons> Persons
        {
            get
            {
                return this.PersonsField;
            }
            set
            {
                this.PersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string abs_path
        {
            get
            {
                return this.abs_pathField;
            }
            set
            {
                this.abs_pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string created_date
        {
            get
            {
                return this.created_dateField;
            }
            set
            {
                this.created_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string @event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string event_date
        {
            get
            {
                return this.event_dateField;
            }
            set
            {
                this.event_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string event_location
        {
            get
            {
                return this.event_locationField;
            }
            set
            {
                this.event_locationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persons", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos", IsReference=true)]
    public partial class Persons : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<MyPhotos.Files> FilesField;
        
        private int IdField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string relationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotos.Files> Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Properties", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos", IsReference=true)]
    public partial class Properties : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<MyPhotos.Files> FilesField;
        
        private int IdField;
        
        private string nameField;
        
        private string valueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotos.Files> Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyPhotos")]
public interface IMyPhotos
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/AddNewFile", ReplyAction="http://tempuri.org/InterfaceFiles/AddNewFileResponse")]
    MyPhotos.Files AddNewFile(MyPhotos.Dto.CreateFileDto fileRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/AddNewFile", ReplyAction="http://tempuri.org/InterfaceFiles/AddNewFileResponse")]
    System.Threading.Tasks.Task<MyPhotos.Files> AddNewFileAsync(MyPhotos.Dto.CreateFileDto fileRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/GetAllFilesPaths", ReplyAction="http://tempuri.org/InterfaceFiles/GetAllFilesPathsResponse")]
    System.Collections.Generic.List<string> GetAllFilesPaths();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/GetAllFilesPaths", ReplyAction="http://tempuri.org/InterfaceFiles/GetAllFilesPathsResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllFilesPathsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/GetFilesByProperty", ReplyAction="http://tempuri.org/InterfaceFiles/GetFilesByPropertyResponse")]
    System.Collections.Generic.List<string> GetFilesByProperty(string propertyName, string propertyValue);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/GetFilesByProperty", ReplyAction="http://tempuri.org/InterfaceFiles/GetFilesByPropertyResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetFilesByPropertyAsync(string propertyName, string propertyValue);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/GetFilesByRelation", ReplyAction="http://tempuri.org/InterfaceFiles/GetFilesByRelationResponse")]
    System.Collections.Generic.List<string> GetFilesByRelation(string relation_type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/GetFilesByRelation", ReplyAction="http://tempuri.org/InterfaceFiles/GetFilesByRelationResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetFilesByRelationAsync(string relation_type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/ModifyFile", ReplyAction="http://tempuri.org/InterfaceFiles/ModifyFileResponse")]
    void ModifyFile(MyPhotos.Dto.CreateFileDto fileRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceFiles/ModifyFile", ReplyAction="http://tempuri.org/InterfaceFiles/ModifyFileResponse")]
    System.Threading.Tasks.Task ModifyFileAsync(MyPhotos.Dto.CreateFileDto fileRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUsers/AddNewPerson", ReplyAction="http://tempuri.org/InterfaceUsers/AddNewPersonResponse")]
    MyPhotos.Persons AddNewPerson(string firstname, string lastname, string relation);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceUsers/AddNewPerson", ReplyAction="http://tempuri.org/InterfaceUsers/AddNewPersonResponse")]
    System.Threading.Tasks.Task<MyPhotos.Persons> AddNewPersonAsync(string firstname, string lastname, string relation);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperties/AddNewProperty", ReplyAction="http://tempuri.org/InterfaceProperties/AddNewPropertyResponse")]
    MyPhotos.Properties AddNewProperty(string name, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperties/AddNewProperty", ReplyAction="http://tempuri.org/InterfaceProperties/AddNewPropertyResponse")]
    System.Threading.Tasks.Task<MyPhotos.Properties> AddNewPropertyAsync(string name, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperties/Check_If_Property_Exists", ReplyAction="http://tempuri.org/InterfaceProperties/Check_If_Property_ExistsResponse")]
    MyPhotos.Properties Check_If_Property_Exists(string propertyName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceProperties/Check_If_Property_Exists", ReplyAction="http://tempuri.org/InterfaceProperties/Check_If_Property_ExistsResponse")]
    System.Threading.Tasks.Task<MyPhotos.Properties> Check_If_Property_ExistsAsync(string propertyName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyPhotosChannel : IMyPhotos, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyPhotosClient : System.ServiceModel.ClientBase<IMyPhotos>, IMyPhotos
{
    
    public MyPhotosClient()
    {
    }
    
    public MyPhotosClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyPhotosClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyPhotosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyPhotosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MyPhotos.Files AddNewFile(MyPhotos.Dto.CreateFileDto fileRequest)
    {
        return base.Channel.AddNewFile(fileRequest);
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Files> AddNewFileAsync(MyPhotos.Dto.CreateFileDto fileRequest)
    {
        return base.Channel.AddNewFileAsync(fileRequest);
    }
    
    public System.Collections.Generic.List<string> GetAllFilesPaths()
    {
        return base.Channel.GetAllFilesPaths();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAllFilesPathsAsync()
    {
        return base.Channel.GetAllFilesPathsAsync();
    }
    
    public System.Collections.Generic.List<string> GetFilesByProperty(string propertyName, string propertyValue)
    {
        return base.Channel.GetFilesByProperty(propertyName, propertyValue);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetFilesByPropertyAsync(string propertyName, string propertyValue)
    {
        return base.Channel.GetFilesByPropertyAsync(propertyName, propertyValue);
    }
    
    public System.Collections.Generic.List<string> GetFilesByRelation(string relation_type)
    {
        return base.Channel.GetFilesByRelation(relation_type);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetFilesByRelationAsync(string relation_type)
    {
        return base.Channel.GetFilesByRelationAsync(relation_type);
    }
    
    public void ModifyFile(MyPhotos.Dto.CreateFileDto fileRequest)
    {
        base.Channel.ModifyFile(fileRequest);
    }
    
    public System.Threading.Tasks.Task ModifyFileAsync(MyPhotos.Dto.CreateFileDto fileRequest)
    {
        return base.Channel.ModifyFileAsync(fileRequest);
    }
    
    public MyPhotos.Persons AddNewPerson(string firstname, string lastname, string relation)
    {
        return base.Channel.AddNewPerson(firstname, lastname, relation);
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Persons> AddNewPersonAsync(string firstname, string lastname, string relation)
    {
        return base.Channel.AddNewPersonAsync(firstname, lastname, relation);
    }
    
    public MyPhotos.Properties AddNewProperty(string name, string value)
    {
        return base.Channel.AddNewProperty(name, value);
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Properties> AddNewPropertyAsync(string name, string value)
    {
        return base.Channel.AddNewPropertyAsync(name, value);
    }
    
    public MyPhotos.Properties Check_If_Property_Exists(string propertyName)
    {
        return base.Channel.Check_If_Property_Exists(propertyName);
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Properties> Check_If_Property_ExistsAsync(string propertyName)
    {
        return base.Channel.Check_If_Property_ExistsAsync(propertyName);
    }
}
